// next/src/components/ui/page-hero.tsx
'use client';

import Link from 'next/link';

import { motion, useReducedMotion } from 'framer-motion';

import { Container } from '@/components/ui/container';

type PageHeroProps = {
  breadcrumb: string;
  headingLight: string;
  headingGradient: string;
  subtitle: string;
};

const HERO_MASK = 'radial-gradient(ellipse 70% 90% at 50% 40%, #000 20%, transparent 75%)';

/** Port of the Nuxt `PageHero` (`BasePageHero`). */
export function PageHero({ breadcrumb, headingLight, headingGradient, subtitle }: PageHeroProps) {
  const reduce = useReducedMotion();
  const fade = (y = 0) =>
    reduce
      ? { initial: false as const }
      : { initial: { opacity: 0, y }, animate: { opacity: 1, y: 0 } };

  return (
    <section className="relative flex min-h-[44vh] flex-col items-center justify-center overflow-hidden bg-ink py-[150px] pb-[70px] text-center min-[400px]:min-h-[46vh]">
      <div
        className="dot-layer"
        style={{ maskImage: HERO_MASK, WebkitMaskImage: HERO_MASK }}
        aria-hidden="true"
      />
      <div
        className="pointer-events-none absolute left-1/2 top-[-160px] h-[500px] w-[500px] -translate-x-1/2 rounded-full bg-accent/15 blur-[90px]"
        aria-hidden="true"
      />
      <div
        className="pointer-events-none absolute bottom-[-160px] right-[8%] h-[360px] w-[360px] rounded-full bg-accent-2/10 blur-[90px]"
        aria-hidden="true"
      />

      <Container className="relative z-10">
        <motion.nav
          {...fade()}
          transition={{ duration: 0.5 }}
          className="mb-[22px] flex items-center justify-center gap-2.5 text-sm text-text-muted"
        >
          <Link href="/" className="text-text-muted transition-colors hover:text-accent">
            Home
          </Link>
          <span className="text-white/25">›</span>
          <span className="text-accent">{breadcrumb}</span>
        </motion.nav>

        <motion.h1
          {...fade(12)}
          transition={{ duration: 0.6, delay: 0.08 }}
          className="font-display text-h1 font-bold leading-[1.08] tracking-tight text-white"
        >
          {headingLight}
          <span className="gradient-text-hero">{headingGradient}</span>
        </motion.h1>

        <motion.p
          {...fade()}
          transition={{ duration: 0.5, delay: 0.16 }}
          className="mx-auto mt-[22px] max-w-[620px] text-hero-sub text-text-muted"
        >
          {subtitle}
        </motion.p>
      </Container>
    </section>
  );
}

// app/components/base/PageHero.vue
<script setup lang="ts">
defineProps<{
  breadcrumb: string
  headingLight: string
  headingGradient: string
  subtitle: string
}>()
</script>

<template>
  <section class="relative flex min-h-[44vh] flex-col items-center justify-center overflow-hidden bg-brand-dark py-[150px] pb-[70px] text-center min-[400px]:min-h-[46vh]">
    <div
      class="dot-layer"
      style="mask-image: radial-gradient(ellipse 70% 90% at 50% 40%, #000 20%, transparent 75%); -webkit-mask-image: radial-gradient(ellipse 70% 90% at 50% 40%, #000 20%, transparent 75%);"
      aria-hidden="true"
    />
    <div
      class="pointer-events-none absolute top-[-160px] left-1/2 h-[500px] w-[500px] -translate-x-1/2 rounded-full bg-brand-cyan/16 blur-[90px]"
      aria-hidden="true"
    />
    <div
      class="pointer-events-none absolute right-[8%] bottom-[-160px] h-[360px] w-[360px] rounded-full bg-brand-green/12 blur-[90px]"
      aria-hidden="true"
    />

    <div class="relative z-10 mx-auto max-w-[1240px] px-4 sm:px-8">
      <nav
        v-motion
        :initial="{ opacity: 0 }"
        :enter="{ opacity: 1, transition: { duration: 500, delay: 0 } }"
        class="mb-[22px] flex items-center justify-center gap-2.5 text-sm text-brand-gray"
      >
        <NuxtLink to="/" class="text-[#94A6BE] transition-colors hover:text-brand-cyan">
          Home
        </NuxtLink>
        <span class="text-white/25">›</span>
        <span class="text-brand-cyan">{{ breadcrumb }}</span>
      </nav>

      <h1
        v-motion
        :initial="{ opacity: 0, y: 12 }"
        :enter="{ opacity: 1, y: 0, transition: { duration: 600, delay: 80 } }"
        class="font-syne text-[clamp(2rem,7.5vw,5rem)] font-bold leading-[1.08] tracking-tight text-white"
      >
        {{ headingLight }}<span class="gradient-text-hero">{{ headingGradient }}</span>
      </h1>

      <p
        v-motion
        :initial="{ opacity: 0 }"
        :enter="{ opacity: 1, transition: { duration: 500, delay: 160 } }"
        class="mx-auto mt-[22px] max-w-[620px] text-[clamp(17px,1.5vw,21px)] text-[#94A6BE]"
      >
        {{ subtitle }}
      </p>
    </div>
  </section>
</template>
